export const languageData = {
    reviews: {
      es: [
        "Me encantó el libro, muy interesante.",
        "Una lectura fascinante, muy recomendable.",
        "El contenido es muy bueno, pero el final me sorprendió.",
        "No me gustó mucho, esperaba algo diferente.",
        "Excelente historia, la mejor que he leído.",
        "Muy bien escrito, pero la trama es predecible.",
        "Un libro increíble, lo devoré en un día.",
        "La narrativa es fluida, pero los personajes podrían ser más profundos.",
        "Una joya literaria, me hizo pensar mucho.",
        "Recomiendo este libro a todos los amantes de la ciencia ficción.",
        "Aunque el principio es lento, el final vale la pena.",
        "Una trama intrigante que mantiene al lector enganchado.",
        "No pude dejar de leerlo, una lectura envolvente.",
        "Lo leí en una tarde, ¡y me encantó!",
        "Es un libro que todo el mundo debería leer, muy inspirador.",
        "Me dejó una sensación agridulce, pero me gustó.",
        "El estilo de escritura es único y cautivador.",
        "Un libro lleno de giros inesperados, no pude anticipar nada.",
        "Historia conmovedora y profunda, me hizo reflexionar sobre la vida.",
        "Aunque el final es triste, la narrativa es impecable.",
        "Una obra maestra de la literatura contemporánea.",
        "Los personajes están bien desarrollados y son entrañables.",
        "La historia se siente auténtica y bien investigada.",
        "El autor tiene una manera de describir los detalles impresionante.",
        "Lectura ligera y entretenida, ideal para el verano.",
        "Es un libro que releería una y otra vez.",
        "Los diálogos son naturales y bien construidos.",
        "No esperaba ese giro en la historia.",
        "Un libro que me mantuvo despierto toda la noche.",
        "Una experiencia de lectura envolvente y gratificante.",
        "Definitivamente lo recomendaría a mis amigos.",
        "Un viaje emocional que recordaré siempre.",
        "La prosa es poética y visual.",
        "Se siente como una obra clásica.",
        "El autor sabe cómo conectar con el lector.",
        "Una historia de amor conmovedora.",
        "Tiene un mensaje profundo y significativo.",
        "Cada página me sorprendía más y más.",
        "Una de las mejores historias que he leído.",
        "Sin duda, una obra que merece la pena.",
        "La narrativa tiene un ritmo perfecto.",
        "Es difícil no enamorarse de los personajes.",
        "El final es tan satisfactorio como inesperado.",
        "Me hizo llorar y reír en partes iguales.",
        "Un retrato profundo de la vida moderna.",
        "La historia se desarrolla de manera orgánica.",
        "Un libro que merece todos los elogios.",
        "Las descripciones son vívidas y detalladas.",
        "Los temas que trata son universales.",
        "Es un libro para todos los públicos.",
        "Me identifiqué con los personajes.",
        "Una historia para reflexionar sobre la vida.",
        "El estilo es ágil y dinámico.",
        "Me dejó queriendo leer más del autor.",
        "Es un libro que desafía los estereotipos.",
        "Los escenarios están bien construidos.",
        "La trama es complicada pero bien resuelta.",
        "Se siente como una película.",
        "Tiene el equilibrio justo de acción y reflexión.",
        "La historia es apasionante y bien desarrollada.",
        "El autor maneja bien los tiempos de la narración.",
        "Cada capítulo te deja queriendo más.",
        "Un libro con mucho que ofrecer.",
        "Los personajes son humanos y reales.",
        "Una trama que engancha desde el inicio.",
        "Perfecto para un fin de semana de lectura.",
        "Es un libro con un mensaje importante.",
        "Cada página es una sorpresa.",
        "No podía parar de leerlo.",
        "Es una obra que se quedará conmigo.",
        "Un libro que se disfruta de principio a fin.",
        "Lo recomendaría sin dudarlo.",
        "La narrativa es sencilla pero poderosa.",
        "Es imposible no engancharse.",
        "Me hizo ver el mundo de otra manera.",
        "Es un libro para leer despacio y disfrutar.",
        "Tiene momentos realmente emotivos.",
        "Una historia muy bien contada.",
        "El final me dejó con ganas de más.",
        "Me sorprendió en todos los sentidos.",
        "Una obra que no se puede dejar pasar.",
        "El autor es un genio de las palabras.",
        "Cada personaje tiene profundidad.",
        "Una trama cautivadora y bien hilada.",
        "Un libro con una narrativa fresca.",
        "Es imposible no encariñarse con los personajes.",
        "Es un libro que inspira.",
        "Una de las mejores lecturas del año.",
        "El final es perfecto para la historia.",
        "Una historia que deja huella.",
        "Tiene un mensaje muy poderoso.",
        "Es como vivir una película.",
        "Cada línea está llena de significado.",
        "Una historia que recordaré siempre.",
        "Tiene algo especial que no puedo describir.",
        "Un libro que trasciende el tiempo.",
        "Me cambió la manera de ver las cosas.",
        "Una obra que merece un lugar especial.",
        "Un clásico instantáneo.",
        "Un libro para los amantes de la buena literatura."
      ],
      fr: [
        "J'ai adoré le livre, très intéressant.",
        "Une lecture fascinante, fortement recommandée.",
        "Le contenu est très bon, mais la fin m'a surpris.",
        "Je ne l'ai pas beaucoup aimé, je m'attendais à quelque chose de différent.",
        "Excellente histoire, la meilleure que j'ai lue.",
        "Très bien écrit, mais l'intrigue est prévisible.",
        "Un livre incroyable, je l'ai fini en une journée.",
        "L'écriture est fluide, mais les personnages pourraient être plus développés.",
        "Un joyau littéraire, cela m'a beaucoup fait réfléchir.",
        "Je recommande ce livre à tous les amateurs de science-fiction.",
        "Bien que le début soit lent, la fin vaut la peine.",
        "Une intrigue captivante qui garde le lecteur en haleine.",
        "Je ne pouvais pas le lâcher, une lecture passionnante.",
        "Je l'ai lu en une seule séance, et j'ai adoré.",
        "Tout le monde devrait lire ce livre, très inspirant.",
        "Il m'a laissé des sentiments partagés, mais j'ai aimé.",
        "Le style d'écriture est unique et captivant.",
        "Un livre plein de rebondissements, je ne pouvais rien anticiper.",
        "Une histoire émouvante et profonde, cela m'a fait réfléchir à la vie.",
        "Bien que la fin soit triste, l'écriture est impeccable.",
        "Un chef-d'œuvre de la littérature contemporaine.",
        "Les personnages sont bien développés et attachants.",
        "L'histoire semble authentique et bien documentée.",
        "L'auteur a une manière incroyable de décrire les détails.",
        "Une lecture légère et divertissante, parfaite pour l'été.",
        "C'est un livre que je relirai encore et encore.",
        "Les dialogues sont naturels et bien construits.",
        "Je ne m'attendais pas à ce rebondissement dans l'histoire.",
        "Un livre qui m'a tenu éveillé toute la nuit.",
        "Une expérience de lecture immersive et gratifiante.",
        "Je le recommanderais sans hésiter à mes amis.",
        "Un voyage émotionnel que je n'oublierai jamais.",
        "La prose est poétique et visuelle.",
        "On dirait un classique.",
        "L'auteur sait comment se connecter aux lecteurs.",
        "Une histoire d'amour touchante.",
        "Il porte un message profond et significatif.",
        "Chaque page me surprenait de plus en plus.",
        "L'une des meilleures histoires que j'ai jamais lues.",
        "Une œuvre qui mérite vraiment des éloges.",
        "Le rythme de la narration est parfait.",
        "Difficile de ne pas tomber amoureux des personnages.",
        "La fin est aussi satisfaisante qu'inattendue.",
        "Cela m'a fait pleurer et rire à parts égales.",
        "Un portrait profond de la vie moderne.",
        "L'histoire se déroule de manière organique.",
        "Un livre qui mérite tous les honneurs.",
        "Les descriptions sont vives et détaillées.",
        "Les thèmes abordés sont universels.",
        "Un livre adapté à tous les publics.",
        "Je me suis identifié aux personnages.",
        "Une histoire pour réfléchir à la vie.",
        "Le style est agile et dynamique.",
        "Il m'a donné envie de lire plus de cet auteur.",
        "Un livre qui défie les stéréotypes.",
        "Les décors sont bien construits.",
        "L'intrigue est complexe mais bien résolue.",
        "On a l'impression de regarder un film.",
        "Équilibre parfait entre action et réflexion.",
        "Une histoire passionnante et bien développée.",
        "L'auteur gère bien le timing de la narration.",
        "Chaque chapitre vous laisse en vouloir plus.",
        "Un livre avec tellement à offrir.",
        "Les personnages sont humains et relatables.",
        "Une intrigue captivante dès le début.",
        "Parfait pour un week-end de lecture.",
        "Un livre avec un message important.",
        "Chaque page est une surprise.",
        "Je ne pouvais pas arrêter de le lire.",
        "C'est une œuvre qui restera avec moi.",
        "Un livre à savourer du début à la fin.",
        "Je le recommanderais sans hésiter.",
        "La narration est simple mais puissante.",
        "Il est impossible de ne pas être accro.",
        "Cela a changé ma façon de voir les choses.",
        "Un livre à lire lentement et à savourer.",
        "Il a des moments vraiment émouvants.",
        "Une histoire très bien racontée.",
        "La fin m'a laissé en vouloir plus.",
        "Cela m'a surpris dans tous les sens.",
        "Une œuvre à ne pas manquer.",
        "L'auteur est un maître des mots.",
        "Chaque personnage a de la profondeur.",
        "Une intrigue captivante et bien ficelée.",
        "Un livre avec une narration fraîche.",
        "Impossible de ne pas s'attacher aux personnages.",
        "Un livre qui inspire.",
        "L'une des meilleures lectures de l'année.",
        "La fin est parfaite pour l'histoire.",
        "Une histoire qui laisse une empreinte.",
        "Il porte un message très puissant.",
        "On a l'impression de vivre un film.",
        "Chaque ligne est pleine de signification.",
        "Une histoire que je me rappellerai toujours.",
        "Il y a quelque chose de spécial que je ne peux décrire.",
        "Un livre qui transcende le temps.",
        "Cela a changé ma façon de voir les choses.",
        "Une œuvre qui mérite une place spéciale.",
        "Un classique instantané.",
        "Un livre pour les amoureux de la grande littérature.",
        "Une lecture qui reste en mémoire.",
        "Un voyage littéraire qui vaut la peine.",
        "Une fin qui laisse sans voix.",
        "Une plume élégante et précise."
      ],
      en: [
       "I loved the book, very interesting.",
  "A fascinating read, highly recommended.",
  "The content is great, but the ending surprised me.",
  "I didn't like it much, I was expecting something different.",
  "Excellent story, the best I've read.",
  "Very well written, but the plot is predictable.",
  "An amazing book, I finished it in a day.",
  "The writing is smooth, but the characters could be more developed.",
  "A literary gem, it made me think a lot.",
  "I recommend this book to all sci-fi lovers.",
  "Although the start is slow, the ending is worth it.",
  "An intriguing plot that keeps the reader hooked.",
  "Couldn't put it down, an engrossing read.",
  "I read it in one sitting and loved it.",
  "Everyone should read this book, very inspiring.",
  "It left me with mixed feelings, but I enjoyed it.",
  "The writing style is unique and captivating.",
  "A book full of twists, I couldn’t anticipate anything.",
  "Touching and deep story, it made me reflect on life.",
  "The ending is sad but the writing is flawless.",
  "A masterpiece of contemporary literature.",
  "Characters are well developed and endearing.",
  "The story feels authentic and well-researched.",
  "The author has a wonderful way with details.",
  "A light and entertaining read, perfect for summer.",
  "It's a book I would re-read again and again.",
  "The dialogues are natural and well-crafted.",
  "Didn't see that twist coming!",
  "A book that kept me awake all night.",
  "An immersive and rewarding reading experience.",
  "I would definitely recommend it to my friends.",
  "An emotional journey I’ll remember.",
  "The prose is poetic and visual.",
  "Feels like a classic.",
  "The author knows how to connect with readers.",
  "A heartwarming love story.",
  "It carries a deep and meaningful message.",
  "Each page surprised me more and more.",
  "One of the best stories I’ve ever read.",
  "A work that truly deserves praise.",
  "The pacing of the narrative is perfect.",
  "Hard not to fall in love with the characters.",
  "The ending is as satisfying as it is unexpected.",
  "It made me cry and laugh in equal parts.",
  "A deep portrait of modern life.",
  "The story unfolds organically.",
  "A book that deserves every accolade.",
  "The descriptions are vivid and detailed.",
  "It addresses universal themes.",
  "A book suitable for all audiences.",
  "I could relate to the characters.",
  "A story to reflect on life.",
  "The style is agile and dynamic.",
  "It made me want to read more from this author.",
  "A book that challenges stereotypes.",
  "Settings are well-constructed.",
  "The plot is complex but well-resolved.",
  "Feels like watching a movie.",
  "Perfect balance of action and thought.",
  "An exciting and well-developed story.",
  "The author handles timing well.",
  "Every chapter leaves you wanting more.",
  "A book with so much to offer.",
  "Characters are human and relatable.",
  "An engaging plot from the start.",
  "Perfect for a weekend read.",
  "A book with an important message.",
  "Every page is a surprise.",
  "I couldn't stop reading it.",
  "A work that will stay with me.",
  "A book to enjoy from start to finish.",
  "I would recommend it without hesitation.",
  "The narrative is simple yet powerful.",
  "It's impossible not to get hooked.",
  "It changed the way I see things.",
  "A book to read slowly and savor.",
  "It has truly emotional moments.",
  "A very well-told story.",
  "The ending left me wanting more.",
  "It surprised me in every way.",
  "A work that cannot be missed.",
  "The author is a master of words.",
  "Every character has depth.",
  "A captivating and well-woven plot.",
  "A book with a fresh narrative.",
  "Impossible not to grow attached to the characters.",
  "A book that inspires.",
  "One of the best reads of the year.",
  "The ending is perfect for the story.",
  "A story that leaves a mark.",
  "It carries a powerful message.",
  "Feels like experiencing a movie.",
  "Every line is full of meaning.",
  "A story I will always remember.",
  "There's something special about it.",
  "A book that transcends time.",
  "It changed my perspective on things.",
  "A work that deserves a special place.",
  "An instant classic.",
  "A book for lovers of great literature."
      ]
    },
    names: {
      es: [
        "Alejandro García", "Isabel Fernández", "Luis Martínez", "Carmen Rodríguez", "Manuel Sánchez", 
        "Sofía Pérez", "Carlos Gómez", "Lucía Hernández", "Diego Jiménez", "María Díaz", 
        "Javier López", "Laura Torres", "Fernando Ruiz", "Elena Ramírez", "Ricardo Morales", 
        "Ana Navarro", "Miguel Ortega", "Sara Castro", "Francisco Vargas", "Marta Prieto", 
        "Jorge Delgado", "Paula Flores", "Antonio Aguilar", "Clara Molina", "José Romero", 
        "Eva Serrano", "David Santiago", "Julia Rivas", "Pablo Ramos", "Alba Márquez", 
        "Rafael León", "Andrea Sánchez", "Héctor Carrillo", "Nuria Muñoz", "Cristina Cano", 
        "Víctor Bautista", "Rosa Vega", "Alberto Gil", "Teresa Peña", "Juan Parra", 
        "Beatriz Lara", "Emilio Blanco", "Patricia Martín", "Enrique Castillo", "Silvia Ferrer", 
        "Ángel Rubio", "Gloria Aguirre", "Pedro Vázquez", "Natalia Campos", "Andrés Ibáñez", 
        "Inés Suárez", "Roberto Medina", "Verónica Guzmán", "Jaime Salas", "Lorena Calvo", 
        "Mario Morales", "Irene Guerrero", "Sergio Ortega", "Raquel Herrera", "Ramón Benítez", 
        "Cristina Molina", "Eduardo Silva", "Sandra Paredes", "Tomás Rubio", "Julia Nieto", 
        "Carlos Duarte", "Carolina Escobar", "Francisco Santamaría", "Mónica Cordero", 
        "Daniel Peña", "Adriana Márquez", "Luis Cabrera", "Diana Beltrán", "José Peña", 
        "Marina Delgado", "Miguel Márquez", "Natalia Navarro", "Gabriel Villanueva", 
        "Lucía Ponce", "Alejandro Cruz", "Paola Serrano", "Víctor Romero", "Sofía Navarro", 
        "Pedro Ruiz", "Eva Moreno", "Esteban Calvo", "Laura Montero", "Juan Pérez", 
        "Teresa Ponce", "Roberto Santana", "Gloria Ortiz", "Antonio Lara", "Ana Herrera", 
        "Jaime Herrera", "Elena Vargas", "Ignacio Muñoz", "Patricia Lozano", "Fernando Medina", 
        "Beatriz García", "Manuel Rosales", "Sara Navarro", "Pablo Pérez", "Andrea Gil"
      ],
      fr: [
        "Louis Martin", "Camille Dubois", "Arthur Lefevre", "Emma Moreau", "Lucas Leroy", 
        "Chloé Simon", "Gabriel Bernard", "Manon Laurent", "Hugo Roux", "Louise Gauthier", 
        "Thomas Garnier", "Clara Dupont", "Maxime Moulin", "Alice Lefevre", "Alexandre Lefort", 
        "Charlotte Maillard", "Julien Perrot", "Lucie Payet", "Nicolas Fontaine", "Léa Pires", 
        "Quentin Robin", "Marie Leroy", "Antoine Dumont", "Julie Millet", "Étienne Blanchard", 
        "Pauline Lefebvre", "Victor Renault", "Sophie Caron", "Baptiste Garnier", "Amélie Lemoine", 
        "Théo Colin", "Élise Leclerc", "Benoît Perrin", "Audrey Marchand", "Émile Mercier", 
        "Céline Chauvin", "Alexis Boucher", "Inès Lambert", "Damien Gillet", "Amandine Durand", 
        "Florian Lebrun", "Noémie Guérin", "Charles Girard", "Marion Lefevre", "Philippe Joly", 
        "Émilie Perrier", "Lucien Martin", "Anaïs Lefort", "Vincent Roche", "Aurélie Renaud", 
        "Tristan Richard", "Nathalie Henry", "Hélène Gautier", "David Dumas", "Pauline Fontaine", 
        "Christophe Rousseau", "Juliette Robert", "Laurent Morel", "Virginie Poirier", "Pierre Langlois", 
        "Sandrine Brunet", "Mathieu Martel", "Éva Lefevre", "Clément Moulin", "Sarah Laurent", 
        "Jules Jacques", "Élisa Lebrun", "Thomas Renard", "Léna Petit", "Félix Colin", 
        "Zoé Lemoine", "Gaspard Noel", "Mélanie Gauthier", "Mathis Dubois", "Coralie Lefebvre", 
        "Augustin Caron", "Lucie Duval", "Sébastien Langlois", "Valérie Giraud", "Nathan Marchand", 
        "Elodie Lefort", "Guillaume Joly", "Claire Blanchard", "Hugo Chauvin", "Julie Dupuis", 
        "Simon Girard", "Oceane Millet", "Aurélien Robert", "Océane Lefevre", "Adrien Caron", 
        "Lise Fontaine", "Martin Dubois", "Alexia Roger", "Didier Lambert", "Solène Morin", 
        "Théodore Rousseau", "Cécile Leclerc", "Mélissa Dumont", "Jacques Brun", "Sophie Blanchard", 
        "Romain Lambert", "Camille Garnier", "Marine Lefevre", "Thibault Dubois", "François Pires"
      ],
      en: [
        "James Smith", "Emily Johnson", "Michael Brown", "Sarah Williams", "David Jones", 
        "Emma Miller", "Christopher Davis", "Olivia Wilson", "Daniel Anderson", "Sophia Taylor", 
        "Matthew Thomas", "Ava Moore", "Anthony Jackson", "Isabella Martin", "Andrew Lee", 
        "Mia Thompson", "Joshua White", "Amelia Harris", "Nicholas Lewis", "Charlotte Clark", 
        "Ryan Walker", "Lily Hall", "Brandon Allen", "Grace Young", "Adam King", 
        "Madison Wright", "Samuel Scott", "Harper Adams", "Nathan Baker", "Ella Nelson", 
        "Jonathan Hill", "Zoey Carter", "Patrick Mitchell", "Penelope Roberts", "Dylan Perez", 
        "Victoria Evans", "Benjamin Collins", "Hannah Turner", "Christian Sanchez", "Lucy Morris", 
        "Kevin Rogers", "Scarlett Reed", "Justin Cook", "Nora Morgan", "Ethan Bell", 
        "Layla Murphy", "Alexander Bailey", "Avery Rivera", "Caleb Cooper", "Eleanor Richardson", 
        "Logan Cox", "Stella Howard", "Kyle Ward", "Hazel Hughes", "Sean Price", 
        "Riley Bennett", "Jason Patterson", "Violet Gray", "Cameron Simmons", "Aurora Foster", 
        "Connor Brooks", "Paisley Powell", "Aaron Long", "Audrey Butler", "Henry Bryant", 
        "Savannah James", "Tyler Russell", "Leah Barnes", "Evan Ross", "Zoey Jenkins", 
        "Austin Myers", "Ellie Perry", "Zachary Russell", "Willow Reed", "Mason Alexander", 
        "Lydia Collins", "Jonathan Hernandez", "Luna Price", "Eli Jenkins", "Brooklyn Ross", 
        "Lucas Sanders", "Anna Stewart", "Owen Green", "Riley Edwards", "Isaac Bryant", 
        "Naomi Hughes", "Hunter Price", "Bella Ward", "Carter Simmons", "Sadie Griffin", 
        "Chase Fisher", "Elena Bennett", "Robert Howard", "Hazel Butler", "Joseph Cooper", 
        "Sophie Bell", "Nathan Russell", "Faith Patterson", "Isaiah Long", "Lucy Brooks", 
        "Charles Hayes", "Paisley Gray", "Jack Morgan", "Jasmine Rivera", "Eric Cooper"
      ]
    },
    publishers: {
      es: [
        "Editorial Santillana", "Grupo Planeta", "Ediciones SM", "Editorial Anagrama", "Alfaguara", 
        "Ediciones B", "Editorial Norma", "RBA Editores", "Penguin Random House España", "Espasa Calpe", 
        "Círculo de Lectores", "Editorial Oceano", "Ediciones Destino", "Editorial Trotta", "Ediciones Akal", 
        "Editorial Cátedra", "Editorial Seix Barral", "Ediciones Siruela", "Editorial Gedisa", "Plaza & Janés", 
        "Tusquets Editores", "Editorial Pre-Textos", "Ediciones Taurus", "Editorial Ariel", "Siglo XXI Editores", 
        "Alianza Editorial", "Editorial Castalia", "Editorial Kairós", "Ediciones Paidós", "Editorial Edebé", 
        "Editorial Milenio", "Ediciones La Cúpula", "Editorial Salvat", "Editorial Juventud", "Editorial Combel", 
        "Grupo Zeta", "Editorial Debate", "Editorial Icaria", "Ediciones Nowtilus", "Ediciones Versal", 
        "Editorial Gredos", "Editorial CCS", "Editorial Gustavo Gili", "Ediciones Laertes", "Ediciones Encuentro", 
        "Editorial Turner", "Libros del Asteroide", "Editorial Planeta DeAgostini", "Editorial Impedimenta", 
        "Editorial Valdemar", "Editorial Alfonsípolis", "Publicaciones Altaya", "Ediciones Urano", "Editorial Debate", 
        "Editorial Crítica", "Editorial Everest", "Eolas Ediciones", "Galaxia Gutenberg", "Editorial Almadía", 
        "Anagrama Argentina", "Editorial Aguilar", "Editorial Troquel", "Fundación Huerta de San Vicente", "Editorial Dossat", 
        "Ediciones Península", "Libros del Zorzal", "Ediciones Altaya", "Ediciones Atalanta", "Editorial Renacimiento", 
        "Editorial Porrúa", "Editorial Edad", "Editorial Kairós", "Nórdica Libros", "Editorial Biblioteca Nueva", 
        "Editorial Nivola", "Editorial El Jinete Azul", "Editorial Canales", "Ediciones El País", "Editorial Impulso", 
        "Fundación José Ortega y Gasset", "Editorial Nuevos Aires", "Ediciones La Torre", "Editorial Loqueleo", 
        "Editorial Casals", "Editorial Bonsái", "Ediciones Aranzadi", "Grupo Círculo", "Ediciones La Galera", 
        "Editorial Zeus", "Editorial Océano Travesía", "Ediciones Subterráneo", "Libros del K.O.", "Editorial Tramuntana", 
        "Edelvives", "Grup 62", "Editorial Hermida Editores", "Editorial Sanz y Torres", "Sexto Piso", 
        "Ediciones Maeva", "Editorial Periférica", "Libros del Zorzal", "Editorial Blume", "Editorial Everest"
      ],
      fr: [
"Éditions Gallimard", "Hachette Livre", "Éditions Grasset", "Éditions Albin Michel", "Éditions du Seuil", 
  "Flammarion", "Éditions Laffont", "Actes Sud", "Éditions Fayard", "Presses de la Cité", 
  "Éditions Odile Jacob", "Bayard Éditions", "Denoël", "Éditions de l'Olivier", "Éditions Calmann-Lévy", 
  "Éditions Lattès", "Éditions Perrin", "Belin", "Éditions Stock", "Éditions Tallandier", 
  "Éditions Larousse", "Le Livre de Poche", "Éditions La Découverte", "Éditions Nathan", "Éditions PUF", 
  "Éditions Plon", "Éditions du Rocher", "Liana Levi", "Éditions du Cerf", "Métailié", 
  "Éditions Milan", "Éditions First", "Éditions de Minuit", "Éditions Pygmalion", "Éditions Les Arènes", 
  "Éditions de La Martinière", "Éditions Alisio", "Les Belles Lettres", "Éditions du Relié", "Éditions Autrement", 
  "Éditions Eyrolles", "Éditions Glénat", "Éditions Dunod", "Fleurus", "Hugo & Cie", 
  "Casterman", "Didier Jeunesse", "L'École des Loisirs", "Éditions Soleil", "Sarbacane", 
  "Éditions Magnard", "Bragelonne", "Gautier-Languereau", "Éditions Thierry Magnier", "Le Cherche Midi", 
  "Éditions Arthaud", "Rouergue", "Éditions du Chêne", "Payot & Rivages", "Les Éditions Noir sur Blanc", 
  "Éditions Prisma", "Le Passage", "Hermann Éditeurs", "Éditions Zulma", "Éditions Lumen", 
  "Éditions Kero", "Le Pommier", "Éditions Hoëbeke", "Librairie Vuibert", "Éditions Graine 2", 
  "Alma Éditeur", "Éditions Dargaud", "Libella", "Éditions ActuSF", "Éditions Iconoclaste", 
  "Editions Métailié", "Editions Phébus", "Éditions Les Allusifs", "Librairie Vuibert", "Éditions Mazarine", 
  "Les Presses de la Renaissance", "Éditions Karthala", "Éditions de Borée", "Éditions Sabine Wespieser", "Éditions Antipodes", 
  "Éditions Max Milo", "Éditions Philippe Picquier", "Éditions du Sous-Sol", "Les Éditions du Petit Chaperon Rouge", "Glénat", 
  "Éditions La Différence", "Éditions D'Ormesson", "Éditions XO", "Éditions Francis Lefebvre", "Éditions Dunod", 
  "Éditions Points", "Éditions Maison des Langues", "Les Éditions de L'Homme", "Éditions de l'Aube", "Éditions Poche"
      ],
      en: [
        "Penguin Books", "HarperCollins", "Simon & Schuster", "Random House", "Scholastic", 
        "Macmillan Publishers", "Hachette Book Group", "Harlequin", "Bloomsbury", "Cengage", 
        "Wiley", "McGraw-Hill Education", "Pearson Education", "Scribner", "Ballantine Books", 
        "St. Martin's Press", "Knopf Doubleday", "Bantam Books", "Crown Publishing", "Little, Brown and Company", 
        "Farrar, Straus and Giroux", "Grove Atlantic", "Hyperion", "Algonquin Books", "Workman Publishing", 
        "Chronicle Books", "Graywolf Press", "Milkweed Editions", "Andrews McMeel Publishing", "Counterpoint Press", 
        "Sourcebooks", "Tor Books", "Flatiron Books", "Avon Books", "Grand Central Publishing", 
        "Delacorte Press", "Riverhead Books", "Putnam", "Dial Books", "Ballantine", 
        "Vintage Books", "Blue Rider Press", "Basic Books", "Arcade Publishing", "PublicAffairs", 
        "Red Hen Press", "University of Chicago Press", "Beacon Press", "Kensington Publishing", "Sterling Publishing", 
        "Dutton", "Picador", "Liveright", "W. W. Norton & Company", "Broadway Books", 
        "Pantheon Books", "Minotaur Books", "Mariner Books", "Portfolio", "Penguin Classics", 
        "Orion Publishing", "Da Capo Press", "Harvard University Press", "Cambridge University Press", "Oxford University Press", 
        "Crown Archetype", "St. Lynn's Press", "Perigee", "Titan Books", "Europa Editions", 
        "Simon Pulse", "Greenwillow Books", "Entangled Publishing", "Dark Horse Books", "Viking Press", 
        "Forge Books", "Regnery Publishing", "Skyhorse Publishing", "Charlesbridge", "Abingdon Press", 
        "Fitzcarraldo Editions", "Akashic Books", "Open Road Media", "Rockridge Press", "Melville House Publishing", 
        "Roaring Brook Press", "Anchor Books", "Counterpoint", "Tundra Books", "Phaidon Press", 
        "Abbeville Press", "MIT Press", "Zondervan", "Vanguard Press", "Vintage International", 
        "Dover Publications", "Sterling Epicure", "Bethany House", "Gray & Company", "Fantagraphics"
      ]
    },
    titles: {
      es: [
        "La sombra del viento", "Cien años de soledad", "El amor en los tiempos del cólera", "Don Quijote de la Mancha", "La casa de los espíritus", 
        "Rayuela", "Pedro Páramo", "Crónica de una muerte anunciada", "El túnel", "La ciudad y los perros", 
        "El Aleph", "Ficciones", "La muerte de Artemio Cruz", "Aura", "Como agua para chocolate", 
        "Los detectives salvajes", "2666", "El otoño del patriarca", "La tregua", "Las venas abiertas de América Latina", 
        "El laberinto de la soledad", "La invención de Morel", "Santos Vega", "La colmena", "María", 
        "El reino de este mundo", "Santa Evita", "El reino de las voces", "La máscara de cristal", "La sombra del águila", 
        "Aura o las violetas", "Amalia", "El beso de la mujer araña", "El siglo de las luces", "La lluvia amarilla", 
        "Palabras en la arena", "La llama doble", "Los pasos perdidos", "La mala hora", "El ingenioso hidalgo Don Quijote", 
        "La región más transparente", "Sobre héroes y tumbas", "La viuda de Montiel", "De amor y de sombra", "Noticias del imperio", 
        "El coronel no tiene quien le escriba", "La casa verde", "Yo, el Supremo", "Los funerales de la Mamá Grande", "Historia de cronopios y de famas", 
        "Las batallas en el desierto", "La isla de los amores infinitos", "La catedral del mar", "El cartero de Neruda", "Las intermitencias de la muerte", 
        "La reina del sur", "El universo en la palma de la mano", "Cuentos de Eva Luna", "La fiesta del Chivo", "Los recuerdos del porvenir", 
        "Travesuras de la niña mala", "Pantaleón y las visitadoras", "Los hijos de la tierra", "La guerra de los cielos", "La estirpe del dragón", 
        "El diosero", "El secreto de sus ojos", "La isla bajo el mar", "La nieta del señor Linh", "El libro de los abrazos", 
        "La mujer habitada", "La guerra del fin del mundo", "La muerte en Venecia", "El testigo", "El huerto de mi amada", 
        "La increíble y triste historia de la cándida Eréndira", "Cuentos completos", "La tentación de lo imposible", "El cuaderno de Maya", "La vida es sueño", 
        "Santos Inocentes", "La balada del café triste", "El pájaro que da cuerda al mundo", "El libro de arena", "El mundo al revés", 
        "El hombre que calculaba", "La caverna", "La hoguera de las vanidades", "Luna caliente", "El último encuentro", 
        "La trinchera infinita", "El secreto de los incas", "El diario de Ana Frank", "La tempestad", "El viejo y el mar", 
        "El Aleph y otros cuentos", "Los santos inocentes", "El general en su laberinto", "La verdad sobre el caso Savolta", "Los relatos de Belcebú a su nieto"
      ],
      fr: [
        "Les Misérables", "Le Comte de Monte-Cristo", "Madame Bovary", "À la recherche du temps perdu", "Les Fleurs du mal", 
        "L'Étranger", "Le Petit Prince", "Candide", "La Nausée", "Les Liaisons dangereuses", 
        "Notre-Dame de Paris", "L'Assommoir", "Bel-Ami", "Thérèse Raquin", "Germinal", 
        "La Condition humaine", "Les Rougon-Macquart", "Voyage au bout de la nuit", "L'Amant", "Le Rouge et le Noir", 
        "Illusions perdues", "Le Père Goriot", "Les Mémoires d'un fou", "La Peste", "Nana", 
        "Les Contemplations", "Le Grand Meaulnes", "Un barrage contre le Pacifique", "La Princesse de Clèves", "Le Diable au corps", 
        "Les Âmes grises", "Le Journal d'un curé de campagne", "La Chambre des officiers", "La Route des Flandres", "La Chartreuse de Parme", 
        "La Symphonie pastorale", "Les Derniers Jours de Charles Baudelaire", "La Reine Margot", "Le Colonel Chabert", "La Vie devant soi", 
        "L'Écume des jours", "Les Chants de Maldoror", "Les Fourmis", "Mémoires d'Hadrien", "Le Silence de la mer", 
        "La Guerre des boutons", "La Métamorphose des cloportes", "La Promesse de l'aube", "Le Château de ma mère", "Le Hussard sur le toit", 
        "Les Particules élémentaires", "Ensemble, c'est tout", "La Condition humaine", "La Gloire de mon père", "Les Rivières pourpres", 
        "La Chambre des dames", "Dans les forêts de Sibérie", "Les Hirondelles de Kaboul", "La Petite Fille de Monsieur Linh", "La Vie mode d'emploi", 
        "La Tête d'un homme", "La Belle et la Bête", "La Nuit des temps", "La Vie en sourdine", "Les Années", 
        "Les Années d'errance", "L'Enchanteur", "Les Bienveillantes", "Le Bal des folles", "Le Baiser au lepreux", 
        "La Joueuse de go", "Les Choses", "Les Nuits blanches", "La Maison Tellier", "Les Misérables", 
        "La Dame aux camélias", "Les Âmes grises", "La Chartreuse de Parme", "La Mort du roi Tsongor", "Le Sabotage amoureux", 
        "Le Testament français", "Les Champs d'honneur", "La Petite Fadette", "La Joie", "Les Tribulations d'un Chinois en Chine", 
        "Les Trois Mousquetaires", "Les Confessions", "Les Enfants du capitaine Grant", "Les Faux-monnayeurs", "Le Joueur d'échecs", 
        "Les Rêveries du promeneur solitaire", "La Possibilité d'une île", "Le Horla", "Les Désorientés", "Le Monde d'hier", 
        "Les Furtifs", "Le Temps retrouvé", "Le Bûcher des vanités", "La Modification", "Le Traité des passions"
      ],
      en:[
        "To Kill a Mockingbird", "Pride and Prejudice", "1984", "The Great Gatsby", "Moby-Dick", 
        "War and Peace", "The Catcher in the Rye", "Ulysses", "The Odyssey", "Great Expectations", 
        "Jane Eyre", "The Hobbit", "The Lord of the Rings", "Little Women", "The Grapes of Wrath", 
        "Brave New World", "Crime and Punishment", "Wuthering Heights", "The Picture of Dorian Gray", "The Scarlet Letter", 
        "Anna Karenina", "The Brothers Karamazov", "The Sun Also Rises", "Dracula", "Fahrenheit 451", 
        "Heart of Darkness", "The Metamorphosis", "Sense and Sensibility", "The Divine Comedy", "The Stranger", 
        "Mansfield Park", "Don Quixote", "One Hundred Years of Solitude", "Lolita", "Catch-22", 
        "Rebecca", "Les Misérables", "Alice's Adventures in Wonderland", "David Copperfield", "A Tale of Two Cities", 
        "The Secret Garden", "Frankenstein", "Gone with the Wind", "The Call of the Wild", "White Fang", 
        "The Sound and the Fury", "Animal Farm", "Lord of the Flies", "The Bell Jar", "The Catcher in the Rye", 
        "Invisible Man", "The Time Machine", "Murder on the Orient Express", "Of Mice and Men", "Dune", 
        "Slaughterhouse-Five", "The Old Man and the Sea", "East of Eden", "The Canterbury Tales", "The Adventures of Huckleberry Finn", 
        "The Iliad", "The Trial", "The Wind in the Willows", "A Wrinkle in Time", "The Joy Luck Club", 
        "Things Fall Apart", "Atonement", "Beloved", "The Help", "The Road", 
        "The Kite Runner", "Life of Pi", "The Girl with the Dragon Tattoo", "The Handmaid's Tale", "Cloud Atlas", 
        "American Gods", "Big Little Lies", "The Shining", "Gone Girl", "Memoirs of a Geisha", 
        "Shogun", "The Girl on the Train", "A Game of Thrones", "The Fault in Our Stars", "The Hunger Games", 
        "Twilight", "Harry Potter and the Sorcerer's Stone", "The Da Vinci Code", "The Outsiders", "The Great Alone", 
        "The Night Circus", "The Alchemist", "The Secret Life of Bees", "Water for Elephants", "The Glass Castle", 
        "The Help", "The Poisonwood Bible", "Wild", "The Art of Racing in the Rain", "The 5th Wave", 
        "The Giver", "Ready Player One", "The Book Thief", "The Lovely Bones", "The Nightingale", 
        "The Light Between Oceans", "Before We Were Strangers", "The Hate U Give", "Where the Crawdads Sing", "All the Light We Cannot See"
      ]
    }
  };